---
# tasks file for sqitch

- block:
  - name: ensure build-essential is installed
    apt:
      name: build-essential
      cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
      install_recommends: no
      state: latest
      update_cache: yes
  
  - name: ensure cpanm is installed
    apt:
      name: cpanminus
      cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
      install_recommends: no
      state: latest
      update_cache: yes
    tags:
      - cpanm

  - name: install sqitch
    cpanm:
      name: DWHEELER/App-Sqitch-{{ sqitch_version }}.tar.gz
      notest: yes
      
  become: true
  become_method: sudo
  tags:
    - sqitch

