---
# tasks file for sqitch

- block:
  - name: install make
    apt:
      name: make
      cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
      install_recommends: no
      state: latest
      update_cache: yes
  
  - name: install libc6-dev
    apt:
      name: libc6-dev
      cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
      install_recommends: no
      state: latest
      update_cache: yes
    tags:
      - libc6-dev
  
  - name: install cpanm
    apt:
      name: cpanminus
      cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
      install_recommends: no
      state: latest
      update_cache: yes
    tags:
      - cpanm

  - name: install libdbd-pg-perl
    apt: 
      name: libdbd-pg-perl
      state: latest
      cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
      install_recommends: no
      update_cache: yes

  - name: install sqitch dependency
    cpanm:
      name: DWHEELER/App-Sqitch-{{ sqitch_version }}.tar.gz
      notest: yes
      installdeps: yes

  - name: install sqitch
    cpanm:
      name: DWHEELER/App-Sqitch-{{ sqitch_version }}.tar.gz
      notest: yes

      
  become: true
  become_method: sudo
  tags:
    - sqitch

